// Drives the real client in headless Chromium: create group -> launch -> play; logs console errors + screenshots.
const { chromium } = require('playwright');
const base = process.argv[2] || 'http://localhost:3000';
const out = __dirname + '/../ref/shots';
require('fs').mkdirSync(out, { recursive: true });
(async () => {
  const b = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'] });
  const page = await b.newPage({ viewport: { width: 1280, height: 800 } });
  page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) console.log('console.' + m.type(), m.text().slice(0, 300)); });
  page.on('pageerror', (e) => console.log('PAGEERROR', e.message, (e.stack || '').split('\n').slice(0, 3).join(' | ')));
  page.on('requestfailed', (r) => console.log('REQFAIL', r.url(), r.failure().errorText));
  page.on('response', (r) => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()); });
  await page.goto(base + '/groups');
  await page.fill('input[name=name]', 'Browser Test');
  await page.check('input[name=private]');
  await Promise.all([page.waitForNavigation(), page.click('#create-group-btn')]);
  console.log('at', page.url());
  await page.waitForTimeout(1500);
  await page.screenshot({ path: out + '/1-group.png' });
  await page.click('#pub-btn'); await page.waitForTimeout(400);
  console.log('after pub isPrivate =', await page.evaluate(() => $('#pub-btn').hasClass('active') || $('.group.container').attr('class')));
  await page.screenshot({ path: out + '/1b-public.png' });
  await page.click('#pug-btn'); await page.waitForTimeout(400);
  await page.screenshot({ path: out + '/1c-private.png' });
  await page.evaluate(() => tagpro.group.socket.emit('setting', { name: 'time', value: '1' }));
  await page.evaluate(() => tagpro.group.socket.emit('groupPlay'));
  await page.waitForURL('**/game', { timeout: 15000 });
  console.log('at', page.url());
  await page.waitForTimeout(3000);
  await page.screenshot({ path: out + '/2-countdown.png' });
  await page.waitForTimeout(19000);
  await page.keyboard.down('ArrowRight'); await page.waitForTimeout(800); await page.keyboard.up('ArrowRight');
  await page.waitForTimeout(500);
  await page.screenshot({ path: out + '/3-playing.png' });
  await page.waitForTimeout(5000);
  const st = await page.evaluate(() => ({ ping: tagpro.ping, state: tagpro.state, me: tagpro.players[tagpro.playerId] && (({ x, y, rx, ry, dead, draw }) => ({ x, y, rx, ry, dead, draw }))(tagpro.players[tagpro.playerId]) }));
  console.log('client state', JSON.stringify(st));
  await b.close();
})().catch((e) => { console.error(e); process.exit(1); });
